### ISSUE TITLE
Definition of timespan

### ISSUE THREAD

**Issue by Princeofthebow** [StochSS/GillesPy2#457]
Hi,
    I have tried to run the following code:

```
import os
import numpy as np
import gillespy2
from gillespy2 import SSACSolver
import time

class BiDimLinearModel(gillespy2.Model):
    def __init__(self, parameter_values=None):
        
        # First call the gillespy2.Model initializer.
        super().__init__(self)

        # Define a parameter that represents the rate of decay.
        supplyrate = gillespy2.Parameter(name='supplyrate', expression=2)
        decayrate = gillespy2.Parameter(name='decayrate', expression=1)
        supplyrateB = gillespy2.Parameter(name='supplyrateB', expression=1)
        decayrateB = gillespy2.Parameter(name='decayrateB', expression=1)
        hillpwr = gillespy2.Parameter(name='hillpwr', expression=0)
        hillpoint = gillespy2.Parameter(name='hillpoint', expression=0)

        self.add_parameter([decayrate, supplyrate, supplyrateB, decayrateB, hillpwr, hillpoint])

        # Define a molecular species representing the protein; "initial_value"
        # sets the number of molecules initial present of simulation.
        A = gillespy2.Species(name='A', initial_value=0);
        B = gillespy2.Species(name='B', initial_value=0);

        self.add_species([A, B])

        r1 = gillespy2.Reaction(name="supplyA", rate = supplyrate,
                                reactants={}, products={A: 1}) # #rate =supplyrate

        r2 = gillespy2.Reaction(name="decayA", rate=decayrate,
                                reactants={A: 1}, products={})

        r3 = gillespy2.Reaction(name="supplyB", propensity_function='(supplyrateB*A)', reactants={},
                                products={B: 1})
        # propensity_function='(pow(A/hillpoint,hillpwr))/(1+pow(A/hillpoint,hillpwr))/2' Hill function

        r4 = gillespy2.Reaction(name="decayB", rate=decayrateB,
                                reactants={B: 1}, products={})

        self.add_reaction([r1, r2, r3, r4])

        # Set the timespan for the simulation.
        self.timespan([0,100]);

model = BiDimLinearModel()
solver = SSACSolver(model)
num_trajectories = 1
serial_results = model.run(solver =solver,number_of_trajectories=num_trajectories)

print(serial_results)
```

and I get the following error:
```
2020-11-02 12:28:00,750 - root - WARNING - Please install/configure 'g++' and 'make' on your system, to ensure that GillesPy2 C solvers will run properly.
2020-11-02 12:28:00,750 - root - WARNING - Please install/configure 'g++' and 'make' on your system, to ensure that GillesPy2 C solvers will run properly.
Traceback (most recent call last):
  File "/home/cfs/gp459/.local/lib/python3.6/site-packages/gillespy2/core/model.py", line 806, in run
    timeout=timeout, **solver_args)
  File "/home/cfs/gp459/.local/lib/python3.6/site-packages/gillespy2/solvers/cpp/ssa_c_solver.py", line 249, in run
    if model.tspan[2] - model.tspan[1] == 1:
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GillesPy2ModelAndRun.py", line 51, in <module>
    serial_results = model.run(solver =solver,number_of_trajectories=num_trajectories)
  File "/home/cfs/gp459/.local/lib/python3.6/site-packages/gillespy2/core/model.py", line 818, in run
    "argument 'solver={}' to run() failed.  Reason Given: {}".format(solver, e))
gillespy2.core.gillespyError.SimulationError: argument 'solver=<gillespy2.solvers.cpp.ssa_c_solver.SSACSolver object at 0x7f56cfe9ba90>' to run() failed.  Reason Given: list index out of range
```

However if I set:

`self.timespan([0,100]);`

to 

`self.timespan([0,50,100]);`

everything seems to run well.

Is this due to my code or is there something under then hood that does not allow to define a 2 element vecotr for time span?[I recall doing it for and older version, i.e 1.4.1 I think)

**Comment by seanebum** [comment]
Hey princeofthebow,

The model timespan is designed to accept a series of fixed-interval time points, so the ideal would be to use something like `self.timespan(np.linspace(0, 50, 101))` (which would return 101 evenly spaced points from 0 to 50).  I do see where the documentation is unclear and I will update it to reflect that!

**Comment by Princeofthebow** [comment]
Hi Sean,
              My main objective - in this setting - would be to compute only the steady state value of the simualtion so I would be defining self.timespan([0,100]); which is indeed a vector of two elements (initial time and end of simulation time).

What you are suggesting uses way more point that I would need giving the whole trasient. I'm on looking for the state at beginning time and end time of simulation so I suspect there may be some bug as the vector of 2  does not work (and it did in ver 1.4.1 I seem to recall) while the vector of three elements does.
