### ISSUE TITLE
AttributeError: 'ODECSolver' object has no attribute 'build_engine'

### ISSUE THREAD

**Issue by briandrawert** [StochSS/GillesPy2#760]
While testing #754, the following code:
```
r4 = model.run(solver=ODECSolver(model))
r4.plot()
```
produced the following warnings:
```
2022-03-28 17:38:07,177 - root - WARNING - model = gillespy2.model is deprecated. Future releases of GillesPy2 may not support this feature.
2022-03-28 17:38:07,177 - root - WARNING - model = gillespy2.model is deprecated. Future releases of GillesPy2 may not support this feature.
Exception ignored in: <function CSolver.__del__ at 0x7f12fdf21c10>
Traceback (most recent call last):
  File "/home/brian/Desktop/research/devils_dftd_modeling/../GillesPy2/gillespy2/solvers/cpp/c_solver.py", line 96, in __del__
    if self.build_engine is None:
AttributeError: 'ODECSolver' object has no attribute 'build_engine'
Exception ignored in: <function CSolver.__del__ at 0x7f12fdf21c10>
Traceback (most recent call last):
  File "/home/brian/Desktop/research/devils_dftd_modeling/../GillesPy2/gillespy2/solvers/cpp/c_solver.py", line 96, in __del__
    if self.build_engine is None:
AttributeError: 'ODECSolver' object has no attribute 'build_engine'
```

**Comment by BryanRumsey** [comment]
Unable to re-create
