### ISSUE TITLE
Unit tests fail due to model too stiff - check/change model

### ISSUE THREAD

**Issue by briandrawert** [StochSS/GillesPy2#772]
```
Run coverage run --source=gillespy2 --omit=gillespy2/solvers/stochkit/* test/run_tests.py -m develop
2022-04-11 19:01:1[6](https://github.com/StochSS/GillesPy2/runs/5978225104?check_suite_focus=true#step:5:6),310 - root - WARNING - Unsupported keyword argument to ODESolver solver: seed
2022-04-11 19:01:16,310 - root - WARNING - Unsupported keyword argument to ODESolver solver: seed
2022-04-11 19:01:16,316 - root - WARNING - Generating duplicate trajectories for model with ODE Solver. Consider running with only 1 trajectory.
2022-04-11 19:01:16,316 - root - WARNING - Generating duplicate trajectories for model with ODE Solver. Consider running with only 1 trajectory.
Traceback (most recent call last):
Running tests in develop mode. Appending repository directory to system path.
  File "test\..\gillespy2\core\model.py", line 10[7](https://github.com/StochSS/GillesPy2/runs/5978225104?check_suite_focus=true#step:5:7)5, in run
    return solver.run(t=t, increment=increment, timeout=timeout, **solver_args)
  File "test\..\gillespy2\solvers\cpp\tau_hybrid_c_solver.py", line 261, in run
    sim_status = self._run(sim_exec, args, decoder, timeout, display_args)
  File "test\..\gillespy2\solvers\cpp\c_solver.py", line 247, in _run
    return self._handle_return_code(return_code)
  File "test\..\gillespy2\solvers\cpp\tau_hybrid_c_solver.py", line 165, in _handle_return_code
    raise ExecutionError("Loop over integrate exceeded, problem space is too stiff")
gillespy2.core.gillespyError.ExecutionError: Loop over integrate exceeded, problem space is too stiff

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test/run_tests.py", line 52, in <module>
    import test_all_solvers
  File "D:\a\GillesPy2\GillesPy2\test\test_all_solvers.py", line 35, in <module>
    class TestAllSolvers(unittest.TestCase):
  File "D:\a\GillesPy2\GillesPy2\test\test_all_solvers.py", line 95, in TestAllSolvers
    labeled_results_more_trajectories[solver.name] = model.run(solver=solver, number_of_trajectories=2)
  File "test\..\gillespy2\core\model.py", line 1079, in run
    ) from e
gillespy2.core.gillespyError.SimulationError: argument 'solver=<gillespy2.solvers.cpp.tau_hybrid_c_solver.TauHybridCSolver object at 0x0000023063F4F04[8](https://github.com/StochSS/GillesPy2/runs/5978225104?check_suite_focus=true#step:5:8)>' to run() failed.  Reason Given: Loop over integrate exceeded, problem space is too stiff
```

**Comment by briandrawert** [comment]
Fixed with TauHybrid refactor
